version: 1
disable_existing_loggers: false

formatters:
  json:
    class: structlog.stdlib.ProcessorFormatter
    processor: structlog.dev.ConsoleRenderer
  
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
    
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/eu_scrape.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  eu_scrape:
    level: DEBUG
    handlers: [console, file]
    propagate: false
    
root:
  level: INFO
  handlers: [console]